import { IconName } from 'ui';

export interface ShowcaseComponent {
  id: string;
  name: string;
  icon: IconName;
}

export const ALL_SHOWCASE_COMPONENTS: ShowcaseComponent[] = [
  { id: 'accordion', name: 'Accordion', icon: 'slide_text' },
  { id: 'avatar', name: 'Avatar', icon: 'person' },
  { id: 'badge', name: 'Badge', icon: 'badge' },
  { id: 'breadcrumb', name: 'Breadcrumb', icon: 'arrow_routing' },
  { id: 'button', name: 'Button', icon: 'button' },
  { id: 'calendar', name: 'Calendar', icon: 'calendar_month' },
  { id: 'card', name: 'Card', icon: 'contact_card' },
  { id: 'carousel', name: 'Carousel', icon: 'arrow_circle_right' },
  { id: 'checkbox', name: 'Checkbox', icon: 'checkbox_checked' },
  { id: 'color', name: 'Color', icon: 'color' },
  { id: 'command-palette', name: 'Command Palette', icon: 'keyboard' },
  { id: 'data-grid', name: 'Data Grid', icon: 'table' },
  { id: 'date', name: 'Date', icon: 'calendar' },
  { id: 'datetime', name: 'Datetime', icon: 'calendar_clock' },
  { id: 'month', name: 'Month', icon: 'calendar_month' },
  { id: 'week', name: 'Week', icon: 'calendar_week_numbers' },
  { id: 'date-range', name: 'Date Range', icon: 'calendar_month' },
  { id: 'dialog', name: 'Dialog', icon: 'window' },
  { id: 'divider', name: 'Divider', icon: 'divider_tall' },
  { id: 'dropdown', name: 'Dropdown', icon: 'apps_list' },
  { id: 'drawer', name: 'Drawer', icon: 'panel_left' },
  { id: 'email', name: 'Email', icon: 'mail' },
  { id: 'empty-state', name: 'Empty State', icon: 'document_dismiss' },
  { id: 'error-state', name: 'Error State', icon: 'error_circle' },
  { id: 'file', name: 'File', icon: 'document' },
  { id: 'icon', name: 'Icon', icon: 'star' },
  { id: 'kbd', name: 'Kbd', icon: 'keyboard' },
  { id: 'loading-state', name: 'Loading State', icon: 'arrow_sync' },
  { id: 'message-bar', name: 'Message Bar', icon: 'alert_badge' },
  { id: 'menu', name: 'Menu', icon: 'group_list' },
  { id: 'nav', name: 'Nav', icon: 'navigation' },
  { id: 'node', name: 'Node', icon: 'circle' },
  { id: 'number', name: 'Number', icon: 'number_row' },
  { id: 'pagination', name: 'Pagination', icon: 'page_fit' },
  { id: 'password', name: 'Password', icon: 'password' },
  { id: 'progress-bar', name: 'Progress Bar', icon: 'spacebar' },
  { id: 'radio-button-group', name: 'Radio Group', icon: 'checkmark_circle' },
  { id: 'rating', name: 'Rating', icon: 'star' },
  {
    id: 'scroll-container',
    name: 'Scroll Container',
    icon: 'dual_screen_vertical_scroll'
  },
  { id: 'scroll-panel', name: 'Scroll Panel', icon: 'dual_screen_vertical_scroll' },
  { id: 'search', name: 'Search', icon: 'search' },
  { id: 'skeleton', name: 'Skeleton', icon: 'checkbox_indeterminate' },
  { id: 'slider', name: 'Slider', icon: 'arrow_maximize' },
  { id: 'speed-dial', name: 'Speed dial', icon: 'add_circle' },
  { id: 'range', name: 'Range', icon: 'arrow_bidirectional_left_right' },
  { id: 'spinner', name: 'Spinner', icon: 'replay' },
  { id: 'splitter', name: 'Splitter', icon: 'split_vertical' },
  { id: 'state-container', name: 'State Container', icon: 'database' },
  { id: 'stepper', name: 'Stepper', icon: 'timeline' },
  { id: 'switch', name: 'Switch', icon: 'tap_single' },
  { id: 'table-of-content', name: 'Table of Content', icon: 'list' },
  { id: 'tabs', name: 'Tabs', icon: 'tabs' },
  { id: 'tag', name: 'Tag', icon: 'tag' },
  { id: 'tel', name: 'Tel', icon: 'call' },
  { id: 'text', name: 'Text', icon: 'text_align_left' },
  { id: 'textarea', name: 'Textarea', icon: 'text_field' },
  { id: 'time', name: 'Time', icon: 'clock' },
  { id: 'time-picker', name: 'Time Picker', icon: 'clock' },
  { id: 'time-span', name: 'Time Span', icon: 'timer' },
  { id: 'toast', name: 'Toast', icon: 'alert' },
  { id: 'toolbar', name: 'Toolbar', icon: 'navigation' },
  { id: 'tooltip', name: 'Tooltip', icon: 'info' },
  { id: 'totp', name: 'TOTP', icon: 'lock_closed' },
  { id: 'tree', name: 'Tree', icon: 'text_bullet_list_tree' },
  { id: 'tree-node', name: 'Tree Node', icon: 'rectangle_landscape' },
  { id: 'url', name: 'URL', icon: 'link' }
];
