import { Type } from '@angular/core';
import {
  LspAccordionPreviewComponent,
  LspAvatarPreviewComponent,
  LspBadgePreviewComponent,
  LspBreadcrumbPreviewComponent,
  LspButtonPreviewComponent,
  LspCalendarPreviewComponent,
  LspCardPreviewComponent,
  LspCarouselPreviewComponent,
  LspCheckboxPreviewComponent,
  LspColorPreviewComponent,
  LspCommandPalettePreviewComponent,
  LspDatePreviewComponent,
  LspDatetimePreviewComponent,
  LspMonthPreviewComponent,
  LspWeekPreviewComponent,
  LspDateRangePreviewComponent,
  LspDialogPreviewComponent,
  LspDividerPreviewComponent,
  LspDropdownPreviewComponent,
  LspDrawerPreviewComponent,
  LspEmailPreviewComponent,
  LspEmptyStatePreviewComponent,
  LspErrorStatePreviewComponent,
  LspFilePreviewComponent,
  LspIconPreviewComponent,
  LspKbdPreviewComponent,
  LspLoadingStatePreviewComponent,
  LspMessageBarPreviewComponent,
  LspMenuPreviewComponent,
} from './landing-surface-previews-a';
import {
  LspNavPreviewComponent,
  LspNodePreviewComponent,
  LspNumberPreviewComponent,
  LspPaginationPreviewComponent,
  LspPasswordPreviewComponent,
  LspProgressBarPreviewComponent,
  LspRadioButtonGroupPreviewComponent,
  LspRatingPreviewComponent,
  LspScrollContainerPreviewComponent,
  LspScrollPanelPreviewComponent,
  LspSearchPreviewComponent,
  LspSkeletonPreviewComponent,
  LspSliderPreviewComponent,
  LspSpeedDialPreviewComponent,
  LspRangePreviewComponent,
  LspSpinnerPreviewComponent,
  LspSplitterPreviewComponent,
  LspStepperPreviewComponent,
  LspSwitchPreviewComponent,
  LspTableOfContentPreviewComponent,
  LspTabsPreviewComponent,
  LspTagPreviewComponent,
  LspTelPreviewComponent,
  LspTextPreviewComponent,
  LspTextareaPreviewComponent,
  LspTimePreviewComponent,
  LspTimePickerPreviewComponent,
  LspTimeSpanPreviewComponent,
  LspToastPreviewComponent,
  LspToolbarPreviewComponent,
  LspTooltipPreviewComponent,
  LspTotpPreviewComponent,
  LspTreePreviewComponent,
  LspTreeNodePreviewComponent,
  LspUrlPreviewComponent,
  LspContextMenuPreviewComponent,
  LspPopoverPreviewComponent,
  LspTimelinePreviewComponent,
} from './landing-surface-previews-b';

export const LANDING_SURFACE_PREVIEW_COMPONENTS: Record<string, Type<unknown>> = {
  accordion: LspAccordionPreviewComponent,
  avatar: LspAvatarPreviewComponent,
  badge: LspBadgePreviewComponent,
  breadcrumb: LspBreadcrumbPreviewComponent,
  button: LspButtonPreviewComponent,
  calendar: LspCalendarPreviewComponent,
  card: LspCardPreviewComponent,
  carousel: LspCarouselPreviewComponent,
  checkbox: LspCheckboxPreviewComponent,
  color: LspColorPreviewComponent,
  'command-palette': LspCommandPalettePreviewComponent,
  'context-menu': LspContextMenuPreviewComponent,
  date: LspDatePreviewComponent,
  datetime: LspDatetimePreviewComponent,
  month: LspMonthPreviewComponent,
  week: LspWeekPreviewComponent,
  'date-range': LspDateRangePreviewComponent,
  dialog: LspDialogPreviewComponent,
  divider: LspDividerPreviewComponent,
  dropdown: LspDropdownPreviewComponent,
  drawer: LspDrawerPreviewComponent,
  email: LspEmailPreviewComponent,
  'empty-state': LspEmptyStatePreviewComponent,
  'error-state': LspErrorStatePreviewComponent,
  file: LspFilePreviewComponent,
  icon: LspIconPreviewComponent,
  kbd: LspKbdPreviewComponent,
  'loading-state': LspLoadingStatePreviewComponent,
  'message-bar': LspMessageBarPreviewComponent,
  menu: LspMenuPreviewComponent,
  nav: LspNavPreviewComponent,
  node: LspNodePreviewComponent,
  number: LspNumberPreviewComponent,
  pagination: LspPaginationPreviewComponent,
  popover: LspPopoverPreviewComponent,
  password: LspPasswordPreviewComponent,
  'progress-bar': LspProgressBarPreviewComponent,
  'radio-button-group': LspRadioButtonGroupPreviewComponent,
  rating: LspRatingPreviewComponent,
  'scroll-container': LspScrollContainerPreviewComponent,
  'scroll-panel': LspScrollPanelPreviewComponent,
  search: LspSearchPreviewComponent,
  skeleton: LspSkeletonPreviewComponent,
  slider: LspSliderPreviewComponent,
  'speed-dial': LspSpeedDialPreviewComponent,
  range: LspRangePreviewComponent,
  spinner: LspSpinnerPreviewComponent,
  splitter: LspSplitterPreviewComponent,
  stepper: LspStepperPreviewComponent,
  switch: LspSwitchPreviewComponent,
  'table-of-content': LspTableOfContentPreviewComponent,
  tabs: LspTabsPreviewComponent,
  tag: LspTagPreviewComponent,
  tel: LspTelPreviewComponent,
  text: LspTextPreviewComponent,
  textarea: LspTextareaPreviewComponent,
  time: LspTimePreviewComponent,
  'time-picker': LspTimePickerPreviewComponent,
  'time-span': LspTimeSpanPreviewComponent,
  timeline: LspTimelinePreviewComponent,
  toast: LspToastPreviewComponent,
  toolbar: LspToolbarPreviewComponent,
  tooltip: LspTooltipPreviewComponent,
  totp: LspTotpPreviewComponent,
  tree: LspTreePreviewComponent,
  'tree-node': LspTreeNodePreviewComponent,
  url: LspUrlPreviewComponent,
};
